### ISSUE TITLE
Give me front-end suggestions

### ISSUE THREAD

**Issue by carlvitzthum** [hms-dbmi/encode#23]
What elements do you want to see changed/added/removed?

**Comment by KorayKirli** [comment]
Hey Carl,
I am not sure how important that is, but as an improvement I have a suggestion. 

Some objects like experiments are turned into collections (/types/experiment.py) and if they have facet information, they turn into nice pages on the website. If the object does not have a type file, /types/base.py  is used.

If there is no facet information in the object/collection, the website outputs the json file. 
[Example](http://4dn-web-dev.us-east-1.elasticbeanstalk.com/labs/ali-mortazavi/)
Since each page can be represented with json format with addition of ?format=json to the url, this seems redundant, and is not easy to grasp. Would there be a way to show the information at least like a table with hierarchy that is easier to look at?
