### ISSUE TITLE
fix js tests for schema destroyer two

### ISSUE THREAD

**Issue by j1z0** [hms-dbmi/encode#83]

**Comment by carlvitzthum** [comment]
The problem was in antibody.js (test: __tests__/antibody-test). Lot component was using regiostry lookup to lookup panel view, which was return IPanel instead of AntibodyStatus, since 'AntibodyLot' is rerouted to 'Item' in registry.js. Hardcoded the use of the AntibodyStatus panel to fix this problem; it will be naturally fixed once object-specific js views are restored.
